### ISSUE TITLE
Reload Loop

### ISSUE THREAD

**Issue by ChrisKader** [michalzaq12/electron-nuxt#145]
Started a new project with this template when I run npm run dev, the application reloads the page over and over until I kill the process.

**Comment by ChrisKader** [comment]
If it helps, my original project did not have an issue until I deleted the node-modules folder and did an npm install. I assume a dependency update broke it but I went through some of the recent updates you made to the library and reverted to previous versions without any luck.

**Comment by ChrisKader** [comment]
Cloned this [branch](https://github.com/michalzaq12/electron-nuxt/tree/dependabot/npm_and_yarn/template/vuetify-2.1.4)
`vue init "./electron-nuxt" test1`
`cd test1`
`npm install`
`npm run dev`

I am no longer experiencing a reload loop.

**Comment by ChrisKader** [comment]
Below options introduced reload loop:

```
? Application Name test1
? Application Id com.example.yourapp
? Application Version 0.0.1
? Project description An electron-nuxt project
? Author
? Select which ui-components framework install Vuetify
? Select which css pre-processor install none
? Select which icon set install none
? Use typescript? No
? Use linting with ESLint? No
? Set up unit testing with vue-test-utils + AVA? No
? Set up end-to-end testing with Spectron + AVA? No
```

**Comment by ChrisKader** [comment]
After a bit of trial and error the reload looping seems to be attributed to the `@nuxt/typescript-build` module.

**Comment by ChrisKader** [comment]
https://github.com/nuxt/typescript/issues/145

**Comment by michalzaq12** [comment]
@ChrisKader, thanks for reporting and your research.
So far the only solution is to use `yarn`

**Comment by ChrisKader** [comment]
Will yarn work with your package without issue? I have been working on my first Electron app and I have gotten used to using this Electron-Nuxt (It is an amazing package!). Currently I do not have any problem with the reload loop (using the dependencies below) but I also dont mind swapping.

`"devDependencies": {
    "@mdi/font": "4.4.95",
    "@nuxt/typescript-build": "^0.1.11",
    "@nuxtjs/vuetify": "1.6.1",
    "@xpda-dev/core": "^0.1.5",
    "@xpda-dev/electron-builder": "^0.1.1",
    "@xpda-dev/electron-launcher": "^0.1.1",
    "@xpda-dev/webpack-step": "^0.1.2",
    "enhanced-resolve": "webpack/enhanced-resolve#master",
    "browser-env": "3.2.6",
    "cross-env": "6.0.3",
    "electron": "5.0.10",
    "electron-builder": "21.2.0",
    "electron-debug": "3.0.1",
    "node-sass": "4.12.0",
    "nuxt": "^2.8.1",
    "roboto-fontface": "0.10.0",
    "sass-loader": "8.0.0",
    "typescript": "3.5.3",
    "vue-devtools": "5.1.3",
    "vuetify": "2.0.11",
    "webpack": "4.41.0",
    "webpack-node-externals": "1.7.2"
  },`

**Comment by michalzaq12** [comment]
Fixed in https://github.com/michalzaq12/electron-nuxt/pull/253
