### ISSUE TITLE
Electron+nuxt+amCharts 4: Unexpected token export

### ISSUE THREAD

**Issue by lightmyfire17** [michalzaq12/electron-nuxt#153]
I want to code a desktop application using Electron, nuxt.js and am4charts. When importing the am4charts core with

`import * as am4core from '@amcharts/amcharts4/core'`

the app returns an error:

`export { System, system } from "./.internal/core/System";
^^^^^^

SyntaxError: Unexpected token export`

My setup:

- latest version of @electron-nuxt
- "@amcharts/amcharts4": "^4.7.1"

I already tried to transpile amCharts in nuxt.config.js using

`  build: {
    transpile: [
      '@amcharts/amcharts4'
    ],
    vendor: ['v-tooltip']
  }`

but without success. How can I fix this issue?

**Comment by michalzaq12** [comment]
Hi @thesheepman ,
Under the hood electron-nuxt extends your nuxt.config.js. 
I don't know why (probably I forgot about it), but `transpile` and `vendor` options were omitted.
Try to directly add line: `transpile: [ '@amcharts/amcharts4' ], vendor: ['v-tooltip']` to `.electron-nuxt/renderer/nuxt.config.js` file.
Please give me feedback if this walkaround have fixed your issue.

**Comment by thesheepman** [comment]
@michalzaq12 
Actually just figured out that the problem is in `@amcharts/amcharts4-geodata`, not in `@amcharts/amcharts4/core` directly, but anyway the `transpile` in `.electron-nuxt/renderer/nuxt.config.js` didn't help.

**Comment by michalzaq12** [comment]
You may also need to add `@amcharts/amcharts4-geodata` to `transpile`

**Comment by thesheepman** [comment]
Yeah, also tried that. Maybe you’ll have time to reproduce it by yourself someday :D

**Comment by michalzaq12** [comment]
Could you send me your `package.json` file ?

**Comment by thesheepman** [comment]
Sure, here it is: https://pastebin.com/25tteYcD
