### ISSUE TITLE
Add DevTron to help in Development

### ISSUE THREAD

**Issue by SrPatinhas** [michalzaq12/electron-nuxt#16]
Maybe add [DevTron](https://github.com/electron-userland/devtron) to help debugging and development

**Comment by michalzaq12** [comment]
@SrPatinhas, sorry for the late answer.
I tried to add DevTron to template but it does not work properly (it stuck all applications [#109](https://github.com/electron-userland/devtron/issues/109)).
In addition, it looks like the whole project is already dead. ( [#111](https://github.com/electron-userland/devtron/issues/111) ).

If something changes, let me know and reopen this thread.
