### ISSUE TITLE
Update to electron 7.0?

### ISSUE THREAD

**Issue by FerLuisxd** [michalzaq12/electron-nuxt#161]
I've noticed that electron-nuxt is still using electron 5.0 therefore chrome 73, electron 7.0 released days ago and it features newer versions of chrome 78
Would like to see it here!

**Comment by MisterJD** [comment]
+1

**Comment by nwittwer** [comment]
Got it working with Electron 7.x by using the `devDependencies` (in `package.json`) listed below.

With the defaults that came with this library, there were some issues using Electron 7 with `core-js`, so I added `core-js@2` and `@babel/runtime-corejs2` as suggested here: https://github.com/nuxt/nuxt.js/issues/6336#issuecomment-561861147. Ideally the extra packages wouldn't be necessary for the official `electron-nuxt` implementation.

```json
{
    "devDependencies": {
        "@babel/runtime-corejs2": "^7.8.3",
        "@xpda-dev/core": "^0.1.5",
        "@xpda-dev/electron-builder": "^0.1.1",
        "@xpda-dev/electron-launcher": "^0.1.1",
        "@xpda-dev/webpack-step": "^0.1.2",
        "browser-env": "3.3.0",
        "core-js": "^2.6.11",
        "cross-env": "6.0.3",
        "deepmerge": "4.2.2",
        "electron": "^7.1.10",
        "electron-builder": "22.2.0",
        "electron-debug": "3.0.1",
        "node-sass": "4.13.1",
        "nuxt": "2.11.0",
        "sass-loader": "8.0.2",
        "vue-devtools": "5.1.3",
        "webpack": "4.41.5",
        "webpack-node-externals": "1.7.2"
    }
}
```

**Comment by michalzaq12** [comment]
Update in https://github.com/michalzaq12/electron-nuxt/pull/253
