### ISSUE TITLE
auto relauching electron when updating codes, old electron instance not exit

### ISSUE THREAD

**Issue by zkcrescent** [michalzaq12/electron-nuxt#169]
no comment

**Comment by zkcrescent** [comment]
paltform: mac 10.13.5

**Comment by adamwhitlock1** [comment]
try putting using this in the src/main/mainWindow.js

```
const winHandler = new BrowserWinHandler({
  height: 600,
  width: 1000
}, !isDev)
```
essentially doesn't allow window to be recreated, therefore preventing duplicate windows from being created after updating code. Hope that helps.
