### ISSUE TITLE
ts error

### ISSUE THREAD

**Issue by Hunlongyu** [michalzaq12/electron-nuxt#289]
![](https://i.loli.net/2020/02/25/KOzVTludCJQbHN1.png)

**Comment by michalzaq12** [comment]
@Hunlongyu The issue is that it's a naming collision between the $loading from nuxt and the one from ElementUI/Buefy

Try adding the following to `src/renderer/tsconfig.js`: 
```js
"compilerOptions": {
    "skipLibCheck": true
}
```

**Comment by michalzaq12** [comment]
Issue link: https://github.com/nuxt/typescript/issues/49

**Comment by Hunlongyu** [comment]
thx
