### ISSUE TITLE
cookie-universal-nuxt get build now working

### ISSUE THREAD

**Issue by SoftBingo** [michalzaq12/electron-nuxt#318]
Hello, I use the cookie-universal-nuxt library with electronjs and nuxtjs and I define it in nuxt.config.js and it works fine but it doesn't work when I package the file

**Comment by michalzaq12** [comment]
In production electron-nuxt app works in file protocol, which does not support cookies. 
You must use [electron cookie API](https://www.electronjs.org/docs/api/cookies) instead.
