### ISSUE TITLE
Electron nuxt main & renderer process with vuex store?

### ISSUE THREAD

**Issue by touqeershafi** [michalzaq12/electron-nuxt#347]
<<TITLE>>

States between main & renderer process

**Comment by michalzaq12** [comment]
Hi @touqeershafi, I don't have any plan to support vuex store sync between processes. This goes beyond the functionality of this template. 

If you need to send data between processes, use electron IPC: [ipcMain](https://www.electronjs.org/docs/api/ipc-main), [ipcRenderer](https://www.electronjs.org/docs/api/ipc-renderer).
