### ISSUE TITLE
Fastify support

### ISSUE THREAD

**Issue by ngth-epi** [michalzaq12/electron-nuxt#356]
Is it possible to combine Nuxt + Fastify within Electron?
I have project which was developed with Nuxt (frontend) and Fastify (API), now I want to combine them all in an Electron app so users can just run it.

**Comment by michalzaq12** [comment]
@ngth-epi yes it is possible. You can use Fastify in main process but I don't see any benefits of using extra (Fastify) API layer. Why do you need an api in local app 😃 ?

**Comment by ngth-epi** [comment]
@michalzaq12 yeah I know it sounds stupid, but I just want to reuse my works as much as possible, anyway thanks for your suggestion, I will look more into this :)
