### ISSUE TITLE
Update to Vue Cli 3

### ISSUE THREAD

**Issue by SrPatinhas** [michalzaq12/electron-nuxt#37]
Just wondering if would take much changes to update the vue cli from the v2 to v3 in this project, being this a recent one and would prevent installing more packages in the machine.

**Comment by michalzaq12** [comment]
Hi @SrPatinhas,
you can use this template with vue cli v3, but you also need to install `vue-init` bridge (v3 does't have this functionality) as it is mentioned in the documentation

`npm install -g @vue/cli` - vue cli v3

`npm install -g @vue/cli-init`

`vue init` now works exactly the same as vue-cli v2

**Comment by SrPatinhas** [comment]
Yes, I did that, and I had no problems, I was just asking to know if there was a possibility to prevent another installation and an easy installation.

**Comment by michalzaq12** [comment]
@SrPatinhas, I did a little research and unfortunately it is impossible at the moment .
I will let you know if something changes
