### ISSUE TITLE
How to navigate to a new page with a custom protocol?

### ISSUE THREAD

**Issue by atn** [michalzaq12/electron-nuxt#400]
I know this may be a newbie question, but how exactly do i navigate to for example: home.vue etc.?

**Comment by austtn** [comment]
follow-up question: Is there a way to navigate to the page in question with a custom electron protocol?

**Comment by austtn** [comment]
Okay, I figured out the first one but still need guidance on how to use the custom protocol to navigate between pages.

**Comment by austtn** [comment]
bump! need an answer asap please 🥺

**Comment by jeremypatrickdahan** [comment]
This looks like a nuxt/vue-router question, not an electron-nuxt question. By default, routing with nuxt depends on your folder structure. If you need to navigate using <nuxt-link> components. Please check out the nuxt documentation https://nuxtjs.org/guide/routing

**Comment by michalzaq12** [comment]
https://github.com/michalzaq12/electron-nuxt/blob/master/template/src/main/mainWindow.js#L9
