### ISSUE TITLE
Bootstrap-Vue Error Avoid mutating

### ISSUE THREAD

**Issue by coyy** [michalzaq12/electron-nuxt#430]
Follow the instructions from: https://bootstrap-vue.org/docs#aliasing-vue-import
Set up an alias to 'vue' in your bundler config
`resolve: {
    alias: {
      vue$: 'vue/dist/vue.esm.js'
    }
  }`
in **.electron-nuxt/renderer/nuxt.config.js** or **/src/renderer/nuxt.config.js** not working

**Comment by michalzaq12** [comment]
Nuxt config is not the same as webpack config.
If you want to add alias, you must use extend option in your nuxt.config.js. 

[How to extend webpack config?](https://nuxtjs.org/faq/extend-webpack/) 
[How to add custom resolve.alias in nuxt.config.js](https://github.com/nuxt/nuxt.js/issues/124)

```js
module.exports = {
  build: {
    extend (config) {
      config.resolve.alias['vue$'] = 'vue/dist/vue.esm.js'
    }
  }
}
```

**Comment by chiragshahklc** [comment]
With extending as you suggested also not working.
![image](https://user-images.githubusercontent.com/27350823/86773096-ce68c980-c072-11ea-99b6-5c9b404eb21a.png)

![image](https://user-images.githubusercontent.com/27350823/86773164-e80a1100-c072-11ea-9f66-4ff5df2c0c92.png)

**Comment by ahoura** [comment]
the issue with bootstrap is related specifically to `.electron-nuxt/renderer/nuxt.config.js` line 29. you gotta configure `nodeExternals` properly, I commented it out and it seems to be working without an issue, but for the original state to stay intact and for bootstrap to work, you need follow the instructions here: https://github.com/bootstrap-vue/bootstrap-vue/issues/3040 and whitelist vue and bootstrap-vue
