### ISSUE TITLE
"404 Not Found" on first installation

### ISSUE THREAD

**Issue by mxswat** [michalzaq12/electron-nuxt#437]
I just did the vue init but I'm unable to try it
In my console, I see Nuxt showing  that ` WARN  Address localhost:9080 is already in use.`

Is it possible to fix this?

**Comment by michalzaq12** [comment]
Try to change `SERVER_PORT` parameter in `.electron-nuxt/config.js` file 😃.

**Comment by mxswat** [comment]
Thanks, I will!
I suggest adding this small issue to the possible problems easy to fix in case another dev finds this.
