### ISSUE TITLE
Build Extend Question

### ISSUE THREAD

**Issue by samuelnunoo** [michalzaq12/electron-nuxt#452]
I'm trying to add a runtime vue compiler and when I modify the build.extend function to do so, it seems not to apply the change.

...src/renderer/nuxt.config.js

This is my code
`  build: { 
    extend (config) { 
      config.resolve.alias['vue'] = 'vue/dist/vue.common'
    }
  },`

I followed precisely the guide here: https://stackoverflow.com/questions/52706863/dynamically-fetch-and-compile-a-template-with-nuxt.
But when I run the application, I get an error that I would expect if the runtime compiler wasn't added: 
![image](https://user-images.githubusercontent.com/38366722/86989883-38a36c00-c150-11ea-81ab-c4410ea09527.png)

Am I doing anything wrong?

**Comment by michalzaq12** [comment]
Nuxt related issue
