### ISSUE TITLE
Cannot read property 'provider' of null  stackTrace

### ISSUE THREAD

**Issue by mumairofficial** [michalzaq12/electron-nuxt#47]
Just initialized project and trying to build binary using `yarn build` and getting error of

> Cannot read property 'provider' of null  stackTrace

OS: Windows 10

it also changed my CLI configurations

![image](https://user-images.githubusercontent.com/6498132/62201733-678e5b00-b3a1-11e9-87be-da3447966527.png)

![image](https://user-images.githubusercontent.com/6498132/62201794-80970c00-b3a1-11e9-9186-59d440a48535.png)

**Comment by michalzaq12** [comment]
Does the same error occur when using `npm run build`, instead of `yarn build`?
