### ISSUE TITLE
module not found error on yarn run dev

### ISSUE THREAD

**Issue by manak1** [michalzaq12/electron-nuxt#488]
Hello, thank you for creating a wonderful project.
I created a new project following the getting started section. 
When I run the command ```yarn run dev```, I got this error below.
I have no idea how to fix this error can someone help me?   Thank you.

<img width="996" alt="スクリーンショット 2020-09-06 23 15 11" src="https://user-images.githubusercontent.com/32151765/92327964-5a5d9880-f098-11ea-8380-10f03d683f48.png">

**Comment by ahoura** [comment]
try

```
yarn add vue-loader
yarn add css-loader
```

**Comment by manak1** [comment]
Thank you for the response.
I added those packages and run the command ```yarn run dev``` and got this error😭
<img width="1411" alt="スクリーンショット 2020-09-08 0 09 09" src="https://user-images.githubusercontent.com/32151765/92400917-a297bc00-f167-11ea-87db-2208c9682756.png">

**Comment by ahoura** [comment]
if I am not mistaken I fixed this issue by upgrading `nuxt`. 

in package.json replace line `"nuxt": "[some version]"` with `"nuxt": "^2.13.0",` 
then remove node_module `rm -rf node_modules/`
reinstall the dependancies again `yarn install`

**Comment by manak1** [comment]
It worked! thank you for your help!! 😊
![Uploading スクリーンショット 2020-09-08 0.25.09.png…]()
