### ISSUE TITLE
Backend server api connection refused

### ISSUE THREAD

**Issue by u-go** [michalzaq12/electron-nuxt#490]
It's impossible to access nuxt server api in production. 

I use nuxt-auth plugin and in dev mode I can access /api/auth trough http://localhost:9080 but in production I got a connection refused error. 

Please help it's a nightmare.

[edit] Forgot in my despair to say thank you first for the great work.

**Comment by michalzaq12** [comment]
Hi @u-go, I don't know how nuxt-auth plugin exactly works, but the main production difference is that there is no server exposed 😄.
Electron-nuxt in production works on file protocol. 
What is returned over /api/auth URL ?

**Comment by u-go** [comment]
Hello, thank you for the answer.
To be clear I can do it other way but my goal is to use almost exactly the same code for my web app and for my electron app.

**Web app**:
nuxt.config.js
```javascript
   ...,
  serverMiddleware: [
    // Api middleware
    // We add /api/login & /api/logout routes
    '~/api'
  ]
```

The api folder is an express server like this
```javascript
import fs from 'fs'
import path from 'path'
import express from 'express'
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const jwt = require('express-jwt')
// Create express router
const router = express.Router()

// Transform req & res to have the same API as express
// So we can use res.status() & res.json()
const app = express()
router.use((req, res, next) => {
  Object.setPrototypeOf(req, app.request)
  Object.setPrototypeOf(res, app.response)
  req.res = res
  res.req = req
  next()
})

router.use(cookieParser())
router.use(bodyParser.json())

const secret = fs.readFileSync(path.join(__dirname, '/private.key'))

router.use(
  jwt({
    secret,
    algorithms: ['RS256']
  }).unless({
    path: ['/api/auth/login']
  })
)

app.use(router)

app.use('/auth/', require('./routes/auth')) // auth handler

// Export the server middleware
export default {
  path: '/api',
  handler: app
}

```
Then in login.vue i use 
```javascript
axios.post('http://localhost:3000', credentials, data => {
  this.$auth.login(data)
  ...
})
```

With electron it works like a charm in dev mode but after build I got a connection refused error. If i got it right it's because there is no server side rendering in prod?

**Comment by sgrund14** [comment]
> Hi @u-go, I don't know how nuxt-auth plugin exactly works, but the main production difference is that there is no server exposed 😄.
> Electron-nuxt in production works on file protocol.
> What is returned over /api/auth URL ?

@michalzaq12 does this mean it is impossible to use server middleware / have a custom api running in the electron app using this package?

**Comment by michalzaq12** [comment]
@sgrund14, you're almost right. "Electron-nuxt" only loads a static Nuxt application, so it is impossible to use server middleware .  However, if you want to set up your own server, you have to configure it yourself in the main process.
