### ISSUE TITLE
Any data persistence capabilities?

### ISSUE THREAD

**Issue by gsidsid** [michalzaq12/electron-nuxt#497]
Is there any ability to persist the Vuex store? Are there any approaches you'd suggest to setting up a library like Vuex Electron or vuex-electron-ipc or Vuex Persist File? None of these are working for me with this boilerplate, exporting the plugins from store/index.js. 

Would really appreciate any direction on data persistence using this boilerplate without needing to rebuild a wheel. Even better if there's a simple way to directly persist Vuex.

**Comment by michalzaq12** [comment]
Try to use https://github.com/robinvdvleuten/vuex-persistedstate#nuxtjs to store vuex data in localstorage.
