### ISSUE TITLE
Local data storage recommendation

### ISSUE THREAD

**Issue by kaanguru** [michalzaq12/electron-nuxt#523]
What are the local data storage options? 

Is there any recommended one that you are using?

Can I use [rxdb](https://github.com/pubkey/rxdb) [lowdb](https://github.com/typicode/lowdb)?

**Comment by michalzaq12** [comment]
The simplest way is to use [electron-store](https://www.npmjs.com/package/electron-store).
But if you need to store large amount or complex data, use for example [TypeORM](https://www.npmjs.com/package/typeorm) with SQLite (I tested this configuration in my side project). 
Rxdb and lowdb should also work.

**Comment by Suyashtnt** [comment]
> The simplest way is to use [electron-store](https://www.npmjs.com/package/electron-store).
> But if you need to store large amount or complex data, use for example [TypeORM](https://www.npmjs.com/package/typeorm) with SQLite (I tested this configuration in my side project).
> Rxdb and lowdb should also work.

how would you implement the SQLite DB?

**Comment by swapnilnandgave08** [comment]
I am not able to add typeorm in electron nuxt project. I am getting import outside module error. Can you help me with this?
