### ISSUE TITLE
Yarn requirement after npm install

### ISSUE THREAD

**Issue by johnyzv** [michalzaq12/electron-nuxt#54]
Hi,
I get this error after `npm install`
![image](https://user-images.githubusercontent.com/1512495/62608297-48934a00-b908-11e9-91e8-c3ff3e02dfe4.png)
However after installing yarn stable version i get into this after retrying the `npm install`
![image](https://user-images.githubusercontent.com/1512495/62609385-5649cf00-b90a-11e9-8060-e8d061298fa3.png)

Sorry if i posted the issue on the wrong project, it seems more related to this [vue-devtools](https://github.com/zce/vue-devtools/).
I managed to make it work by installing without scripts `npm install --no-scripts` and after `npm install electron`

PS: When i vue init this template a month ago i didn't have any of these issues, but i think i was running the command from wsl bash

**Comment by michalzaq12** [comment]
It was an internal vue-devtools error. Update the package 🚀
