### ISSUE TITLE
linux app.getPath is Electron

### ISSUE THREAD

**Issue by Suyashtnt** [michalzaq12/electron-nuxt#586]
app.getPath('userData') points to `/home/home/.config/Electron`. This should be `/home/home/.config/glowsquid-next` as that is my project name

**Comment by michalzaq12** [comment]
In development, method `app.getPath('userData')` returns the Electron folder, but the method called in the built application should return `/home/home/.config/glowsquid-next`

**Comment by Suyashtnt** [comment]
yeah i figured that out, there should be a workaround but for now its fine
