### ISSUE TITLE
Load JS package cause error: is not a constructor

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [michalzaq12/electron-nuxt#655]
Hello,

1. Thank you for this awesome template :).

2. I'm facing this problem while using this package:
`npm i plain-draggable`
After install it, add this to:
`/src/renderer/pages/index.vue`
2.1. The commented code not working too.
```
<template>
  <div class="container">
    <div id="draggable" > drage me </div>
  </div>
</template>
<script>
import PlainDraggable from 'plain-draggable'
// import { PlainDraggable } from 'plain-draggable'
// import * as PlainDraggable from 'plain-draggable'

export default {
  mounted () {
    var draggable = new PlainDraggable(document.getElementById('draggable'))
  }
}
</script>

```

I get this error:
`plain_draggable__WEBPACK_IMPORTED_MODULE_6__ is not a constructor`

3. I have added this `libraryTarget: "umd"` also to: `.electron-nuxt/index.js`
3.1 the commented code not working too.
```
const webpackConfig = Webpack.getBaseConfig({
  entry: isDev
    ? path.join(MAIN_PROCESS_DIR, 'boot/index.dev.js')
    : path.join(MAIN_PROCESS_DIR, 'boot/index.prod.js'),
  output: {
    filename: 'index.js',
    path: path.join(DIST_DIR, 'main'),
    libraryTarget: "umd"
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.resourcesPath': resourcesPath.mainProcess(),
      'process.env.DEV_SERVER_URL': `'${SERVER_HOST}:${SERVER_PORT}'`
    })
  ],
  // module: {
  //   rules: [
  //     {
  //       test: require('path').resolve(__dirname, 'node_modules/plain-draggable/'),
  //       use: [{
  //         loader: 'skeleton-loader',
  //         options: {procedure: content => `${content}export default PlainDraggable`}
  //       }]
  //     }
  //   ]
  // }
})
```

4. I have tried this package using `vite template` and it works for me well.
https://github.com/lemueldls/electron-nuxt-vite

5. In simple nuxt template works well too.

6. Also works in simple electron template.

- So I think its from webpack; not loading the package correctly or somthing else?

Thank you.

**Comment by michalzaq12** [comment]
This issue is not related to the Electron-nuxt package.
https://github.com/anseki/plain-draggable/issues/2
