### ISSUE TITLE
Main Typescript support

### ISSUE THREAD

**Issue by leohubert** [michalzaq12/electron-nuxt#668]
Hi there,
I just want to know the main typescript support is always planned ?

If it’s started do you need help ?

**Comment by michalzaq12** [comment]
Hi @leohubert, typescript support should work, but it is hard to maintain this number of template versions using the vue-cli template engine.

To enable TypeSccript support in main process, you need to rewrite main files to ts, 
and in .electron-nuxt/index.js file ((https://github.com/michalzaq12/electron-nuxt/blob/master/template/.electron-nuxt/index.js#L36)) change `Webpack.getBaseConfig` to `Webpack.getTypescriptConfig`,  you can optionally provide the path to tsconfig.json, for example: 

```js
const webpackConfig = Webpack.getTypescriptConfig({
  tsconfig: './tsconfig.json',
  entry: './index.ts',
  output: {
    filename: 'index.js',
    path: './dist',
  },
})
```

**Comment by leohubert** [comment]
Hi @michalzaq12, yep I’ve see that and it's work great. 

Just need to add this:
```php
webpackConfig.resolve.extensions.push('.ts', '.tsx')
```

I've create a PR here to fix the problem about getTypescriptConfig function.
https://github.com/michalzaq12/xpda-dev/pull/4
