### ISSUE TITLE
Axios requests denied by CORS policy after upgrade to 1.7.0

### ISSUE THREAD

**Issue by tomboolean** [michalzaq12/electron-nuxt#680]
Access to XMLHttpRequest at 'http://myrestapi.com/*******' from origin 'app://.' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Does [this line](https://github.com/michalzaq12/electron-nuxt/blob/215fc9f7c6e87029e51ed35ffd71481cc19d377b/template/src/main/BrowserWinHandler.js#L79) fix some other issue from before? Forgive my ignorance on this matter, I am green to electron and CORS policy management for electron.

I can add this new Origin of `app://.` to my CORS, server-side but is this necessary? Is there a better way to solve this? Thanks! Also, if there is a better forum for this let me know - I didn't notice one in the README or documentation specified.

Thank you for all you do ❤️❤️❤️

**Comment by michalzaq12** [comment]
There are very few resources about electron application in production. Opening the server in production (same as in development) is a bad idea as we need to open a new port which can sometimes cause a warning / error (action requires additional permissions).
Before 1.7.0, Electron-Nuxt used raw file protocol (file: ///index.html) but it broke a lot of things (js packets / security vulnerability).
In version 1.7.0 I added a new way inspired by the https://github.com/nklayman/vue-cli-plugin-electron-builder template: custom `app` protocol (http emulation) that only points to the built application. The host is set to `.` but it can be changed as it is always omitted from the absolute path translation (`app: //./index.html` -> `C://user/electron_app/index.html`).
In my application (created with Electron-Nuxt) I added `app: //.` to the allowed sources. However, I am not sure if this is the best solution.

**Comment by tomboolean** [comment]
Ah, I see. Thanks for filling me in on what this is intended to fix. I'm learning a lot.

I was able to enable our connection to our REST API back by adding `app://.` to my CORS whitelist on my REST API's side. But, I still get errors with Gravatar calls:

Access to XMLHttpRequest at 'https://www.gravatar.com/*******************.json' from origin 'app://.' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by tomboolean** [comment]
I'll think more on how I can prevent `app://.` from being sent as the origin and read up more on CORS.
