### ISSUE TITLE
MacOS -  reopen window from dock problem

### ISSUE THREAD

**Issue by namjeongho** [michalzaq12/electron-nuxt#726]
When reopen window from dock after close window in MacOS, 
page url is not loaded.

It seems like that main process don't invoke the create callback function.

If I modify below code, it works well

> [src/main/BrowserWinHandler.js]

```
  onCreated (callback) {
    if (this.browserWindow !== null) return callback(this.browserWindow);
    this._eventEmitter.once('created', () => {
      callback(this.browserWindow)
    })
  }

```

` this._eventEmitter.once(   =>   this._eventEmitter.on(`

Thanks.

**Comment by zaosoula** [comment]
Hello, did you found a fix?

**Comment by michalzaq12** [comment]
`app.on('activate', () => show/recreate window)`

**Comment by stevebauman** [comment]
Omg I was banging my head on the wall for this for hours! Thank you @namjeongho!!

This should really be updated in the main repo. For anyone else having this issue (as @namjeongho has shown):

**From**:
```js
this._eventEmitter.once('created', () => {
  callback(this.browserWindow)
})
```

**To**:
```js
this._eventEmitter.on('created', () => {
  callback(this.browserWindow)
})
```

The event emitter is only listening for the `created` event "once". It should instead be set to "on" to always listen for the `created` event.

Hope this saves some other poor souls hours of debugging.
