### ISSUE TITLE
Getting a Manifest error during npm run dev

### ISSUE THREAD

**Issue by wdamaral** [michalzaq12/electron-nuxt#74]
Just starting with your solution.
I've installed the boilerplate by following the documentation you have however, when I run npm run dev, I get an annoying error message. Not sure if it'll impact any other thing later.
The application seems to be working fine but I don't see the button "Relaunch Electron", as seen on your preview image

![image](https://user-images.githubusercontent.com/32019817/63903848-f7451a80-c9dc-11e9-951c-5ce724bd9c45.png)

![image](https://user-images.githubusercontent.com/32019817/63903942-4f7c1c80-c9dd-11e9-9389-1e13baf7b631.png)

**Comment by michalzaq12** [comment]
@wdamaral , thanks for reporting the issue.
Fixed in #78
