### ISSUE TITLE
How to make build for all platforms?

### ISSUE THREAD

**Issue by kentforth** [michalzaq12/electron-nuxt#775]
When I run command yarn build. The project creates finished file but only for my platform(Macos)
How to make build finished files for all platforms? (Linux, Macos, Windows)

**Comment by confuseder** [comment]
+1 I also have this problem。

**Comment by michalzaq12** [comment]
https://michalzaq12.github.io/electron-nuxt/guide/#electron-builder-arguments-1-6-0
`yarn build --win`
