### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ThatTonybo** [michalzaq12/electron-nuxt#776]
Made a fresh app from init, installed deps and I get a 404 on first load.
![image](https://user-images.githubusercontent.com/28176227/128439721-3143260b-1a21-4fcf-9f76-454e52e4ba91.png)

**Comment by Gruce** [comment]
Try to make your own index.vue page

**Comment by Gruce** [comment]
@Mwpereira Please make your own index.vue page

**Comment by Mwpereira** [comment]
> @Mwpereira Please make your own index.vue page

I did, unfortunately I still get the error.

**Comment by Gruce** [comment]
> > @Mwpereira Please make your own index.vue page
> 
> I did, unfortunately I still get the error.

Please go to ".electron-nuxt" then open "config.js" then change SERVER_PORT to 3000.

**Comment by DollarAkshay** [comment]
This usually happens if there is another app running on the same port.
In my case it was Logitech GHub
