### ISSUE TITLE
Run nuxt web application

### ISSUE THREAD

**Issue by niklashaug** [michalzaq12/electron-nuxt#781]
Is it possible to also run the nuxt app without electron so that I can share the same code for the electron desktop app and the nuxt web app?

**Comment by zaosoula** [comment]
You can make the window load a URL (in your case to your web app)

``src/main/mainWindow.js``
```js
 winHandler.onCreated(_browserWindow => {
  //winHandler.loadPage("/");
  // Or load custom url
  _browserWindow.loadURL('https://google.com')
});
```
