### ISSUE TITLE
[BUG] Remote is Deprecated

### ISSUE THREAD

**Issue by BlackYuzia** [michalzaq12/electron-nuxt#786]
Hi there, thx for that template.

But, how I find in `pages/index.vue`, you use `remote` from `electron`.
As [**docs**](https://runebook.dev/en/docs/electron/api/remote) say `remote` is deprecated.  

You can replace deprecated `remote` by [`ipcRenderer`](https://runebook.dev/en/docs/electron/api/ipc-renderer) and [`ipcMain`](https://runebook.dev/en/docs/electron/api/ipc-main).
```js
import { remote } from 'electron'

// inside vue
openURL (url) {
  remote.shell.openExternal(url)
}
```
That also mean what `remote.shell...` won't work and return error because `remote` is undefined.

**Comment by michalzaq12** [comment]
Fixed in 1.8.1
