### ISSUE TITLE
Auto Import of Components is not working

### ISSUE THREAD

**Issue by MentalGear** [michalzaq12/electron-nuxt#787]
Even when setting `components: true` in `nuxt.config.js`, auto import is not working and components need manual addition.
Specifying the components path as `@/renderer/components` returns the error that this component path can't be found.

**Comment by PhelixOchieng** [comment]
@MentalGear
### Issue 1: "setting components: true in nuxt.config.js, auto import is not working"
Please provide the following additional info information

- nuxt version in `package.json`
- your components directory folder structure for the component you are trying to use

### Issue 2: "@/renderer/components returns the error that this component path can't be found"
#### Fix:
Replace `@/renderer/components` with `@/components`

**Comment by MentalGear** [comment]
Sorry fir the confusion. 'components: true' works fine indeed, but I had to manually restart the dev server.
In previous nuxt dev environments, changing nuxt.config.js hot reloaded / rebuild automatically.
