### ISSUE TITLE
Vuetify is not being bootstrapped

### ISSUE THREAD

**Issue by wdamaral** [michalzaq12/electron-nuxt#88]
I'm trying to start with the boilerplate but I'm having issues to bootstrap Vuetify.
I have installed the boilerplate with Vuetify and SASS. The first run is ok but if I add, for example, a `<v-app-bar>` to my template, I get an error message as follows:

![image](https://user-images.githubusercontent.com/32019817/64130594-57e3a700-cd91-11e9-8bbe-d98b3bf6836b.png)

The only thing I did was to change the header.vue and add the `<v-app-bar>`

**Comment by michalzaq12** [comment]
Fixed in #91. Try to use new template version (v1.3.0). 
You may need to change default layout template to: 
```
<template>
  <v-app>
    <app-header />
    <nuxt />
  </v-app>
</template>
```
